### ISSUE TITLE
"pip install hotfilefinder" does not work

### ISSUE THREAD

**Issue by aevernon** [colinhowe/hotfilefinder#1]
```
$ sudo pip install hotfilefinder
Downloading/unpacking hotfilefinder
  Could not find any downloads that satisfy the requirement hotfilefinder
Cleaning up...
No distributions at all found for hotfilefinder
Storing complete log in /root/.pip/pip.log
```

I'm using Fedora 20 with pip 1.4.1.

**Comment by colinhowe** [comment]
Can you try the below?

```
pip install -v hotfilefinder
```

It's on pypi and it works on a few machines I've tried it on... I don't have Fedora though so not sure if that's related :(

**Comment by aevernon** [comment]
If I run `pip install -v hotfilefinder`, this is what I see in ~/.pip/pip.log:

```
Downloading/unpacking hotfilefinder

  Getting page https://pypi.python.org/simple/hotfilefinder/
  URLs to search for versions for hotfilefinder:
  * https://pypi.python.org/simple/hotfilefinder/
  Analyzing links from page https://pypi.python.org/simple/hotfilefinder/
  Could not find any downloads that satisfy the requirement hotfilefinder

Cleaning up...

  Removing temporary dir /tmp/pip_build_aev...

No distributions at all found for hotfilefinder

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1085, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/site-packages/pip/index.py", line 265, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for hotfilefinder
```
